'use client'

import { useEffect, useState, type CSSProperties } from 'react'
import { ArrowUpRight, ChevronLeft, ChevronRight, Menu, Pause, Play, Zap } from 'lucide-react'
import { AuthNav } from '@/components/auth-nav'

const defaultSlides = [
  { eyebrow: 'ARCHITECTURAL LIGHTING / 01', title: 'Light shapes\nwhat matters.', description: 'Fazco engineers intelligent electrical systems and expressive lighting for architecture that feels alive.', image: 'https://images.unsplash.com/photo-1511818966892-d7d671e672a2?auto=format&fit=crop&w=2200&q=90', label: 'Residential landmark / Tehran' },
  { eyebrow: 'INTERIOR LIGHTING / 02', title: 'Every space\nhas a pulse.', description: 'A considered balance of atmosphere, performance and precision — from the first sketch to the final switch.', image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=2200&q=90', label: 'Private residence / Dubai' },
  { eyebrow: 'SMART BUILDING SYSTEMS / 03', title: 'Powering the\nnext perspective.', description: 'Connected infrastructure that makes ambitious places safer, smarter and more sustainable.', image: 'https://images.unsplash.com/photo-1487958449943-2429e8be8625?auto=format&fit=crop&w=2200&q=90', label: 'Cultural campus / Shiraz' },
]
type Slide = (typeof defaultSlides)[number] & { video?: string }

const services = [
  ['01', 'Facade lighting', 'Give architecture a distinctive presence after dark.'],
  ['02', 'Interior lighting', 'Make every mood, material and movement feel intentional.'],
  ['03', 'Building electrical', 'Reliable, intelligent infrastructure engineered to last.'],
]

export default function Page() {
  const [slides, setSlides] = useState<Slide[]>(defaultSlides)
  const [active, setActive] = useState(0)
  const [playing, setPlaying] = useState(true)
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false)
  const [pointer, setPointer] = useState({ x: 50, y: 50 })
  const [scrollProgress, setScrollProgress] = useState(0)
  const [projects, setProjects] = useState<Array<{ id: string; title: string; meta: string; description: string; image: string; video: string }>>([])
  const [motion, setMotion] = useState({ video: '', eyebrow: '/ In motion', title: 'Systems that move with you.', description: 'A glimpse of the quiet precision behind every Fazco project.', label: 'Fazco company film' })
  const [packageCopy, setPackageCopy] = useState<Record<string, string>>({})
  const [serviceCopy, setServiceCopy] = useState<Record<string, string>>({})
  const [standardCopy, setStandardCopy] = useState<Record<string, string>>({})

  useEffect(() => {
    let cancelled = false
    fetch('/api/banners').then((response) => response.json()).then((data) => {
      if (cancelled || !Array.isArray(data.banners) || data.banners.length === 0) return
      setSlides(data.banners.map((banner: { eyebrow: string; title: string; subtitle: string; image: string; video: string; label: string }, index: number) => ({ eyebrow: banner.eyebrow || `FAZCO / ${String(index + 1).padStart(2, '0')}`, title: banner.title, description: banner.subtitle, image: banner.image, video: banner.video, label: banner.label || 'Fazco project' })))
      setActive(0)
    }).catch(() => undefined)
    return () => { cancelled = true }
  }, [])

  useEffect(() => {
    fetch('/api/showcase').then((response) => response.json()).then((data) => { if (Array.isArray(data.items)) setProjects(data.items) }).catch(() => undefined)
    fetch('/api/site-settings').then((response) => response.json()).then((data) => { if (data.motion) setMotion((current) => ({ ...current, ...data.motion })); if (data.packages) setPackageCopy(data.packages); if (data.services) setServiceCopy(data.services); if (data.standard) setStandardCopy(data.standard) }).catch(() => undefined)
  }, [])

  useEffect(() => {
    if (!playing || slides.length < 2) return
    const timer = window.setInterval(() => setActive((current) => (current + 1) % slides.length), 6500)
    return () => window.clearInterval(timer)
  }, [playing, slides.length])

  useEffect(() => {
    const revealItems = Array.from(document.querySelectorAll<HTMLElement>('[data-reveal]'))
    if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) { revealItems.forEach((item) => item.dataset.revealed = 'true'); return }
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.setAttribute('data-revealed', 'true'); observer.unobserve(entry.target) } }), { threshold: 0.12, rootMargin: '0px 0px -8% 0px' })
    revealItems.forEach((item) => observer.observe(item))
    return () => observer.disconnect()
  }, [])

  useEffect(() => {
    const onScroll = () => {
      const max = document.documentElement.scrollHeight - window.innerHeight
      setScrollProgress(max > 0 ? window.scrollY / max : 0)
    }
    onScroll()
    window.addEventListener('scroll', onScroll, { passive: true })
    return () => window.removeEventListener('scroll', onScroll)
  }, [])

  // Keep the active index valid when the admin adds, removes, or disables slides.
  const safeActive = slides.length > 0 ? Math.min(active, slides.length - 1) : 0
  const slide = slides[safeActive] ?? defaultSlides[0]
  const configuredServices = [...services, ...(['04', '05', '06'] as const).filter((key) => serviceCopy[`service_${key}_active`] === 'on').map((key) => [key, serviceCopy[`service_${key}_title`] || `Service ${key}`, serviceCopy[`service_${key}_description`] || 'A considered service for spaces with a point of view.'] as [string, string, string])]
  
  return (
    <main id="top" className="min-h-screen overflow-hidden bg-background text-foreground selection:bg-primary selection:text-primary-foreground">
      <div className="scroll-progress" style={{ transform: `scaleX(${scrollProgress})` }} aria-hidden="true" />
      <section className="hero-motion relative min-h-[720px] h-screen max-h-[960px] overflow-hidden bg-[#071c22] text-white" onMouseMove={(event) => { const rect = event.currentTarget.getBoundingClientRect(); setPointer({ x: ((event.clientX - rect.left) / rect.width) * 100, y: ((event.clientY - rect.top) / rect.height) * 100 }) }} style={{ '--pointer-x': `${pointer.x}%`, '--pointer-y': `${pointer.y}%` } as CSSProperties}>
        <div className="hero-cursor-glow" aria-hidden="true" />
        {slide.video ? <video key={slide.video} className="absolute inset-0 size-full object-cover transition-all duration-1000" src={slide.video} poster={slide.image || undefined} autoPlay muted loop playsInline aria-label={slide.label || 'Fazco project film'} /> : <div className="absolute inset-0 bg-cover bg-center transition-all duration-1000" style={{ backgroundImage: `url(${slide.image})` }} />}
        <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(3,17,21,.9),rgba(3,17,21,.18)_68%,rgba(3,17,21,.45))]" />
        <div className="absolute inset-x-0 bottom-0 h-48 bg-gradient-to-t from-[#071c22] to-transparent" />
        <header className="site-header fixed inset-x-0 top-4 z-40 mx-auto flex max-w-6xl items-center justify-between rounded-full border border-white/20 bg-[#071c22]/55 px-4 py-3 text-white shadow-[0_18px_70px_rgba(3,17,21,.24)] backdrop-blur-2xl md:top-5 md:px-5">
          <a href="#top" className="flex shrink-0 items-center gap-2.5" aria-label="Fazco home"><img src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/photo_2_2026-07-12_18-43-01-al0Dj96HxHHDIA9rxM6hQR2SP0I5mp.jpg" alt="Fazco logo" className="size-9 rounded-full object-cover ring-1 ring-white/35" /><span className="hidden text-sm font-semibold tracking-[.22em] sm:block">FAZCO</span></a>
          <nav className="glass-nav hidden items-center gap-1 rounded-full border border-white/10 bg-white/[.06] p-1 text-sm md:flex" aria-label="Primary navigation"><a href="#about" className="glass-nav-link">About</a><a href="#services" className="glass-nav-link">Services</a><a href="/shop" className="glass-nav-link">Shop</a><a href="#projects" className="glass-nav-link">Projects</a><a href="#contact" className="glass-nav-link">Contact</a></nav>
          <div className="flex items-center gap-2"><AuthNav /><a href="#contact" className="glass-button hidden items-center gap-2 rounded-full px-3.5 py-2 text-xs lg:flex"><span>Start a project</span><Menu className="size-3.5" /></a><button type="button" className="glass-button inline-flex size-10 items-center justify-center rounded-full md:hidden" onClick={() => setMobileMenuOpen((open) => !open)} aria-expanded={mobileMenuOpen} aria-controls="mobile-primary-navigation" aria-label={mobileMenuOpen ? 'Close navigation menu' : 'Open navigation menu'}><span className={`hamburger-icon ${mobileMenuOpen ? 'is-open' : ''}`} aria-hidden="true"><span /><span /><span /></span></button></div>
          {mobileMenuOpen && <nav id="mobile-primary-navigation" className="glass-mobile-menu absolute inset-x-2 top-[calc(100%+0.65rem)] flex flex-col gap-1 rounded-3xl border border-white/20 p-2 text-sm md:hidden" aria-label="Mobile primary navigation"><a href="#about" className="glass-nav-link" onClick={() => setMobileMenuOpen(false)}>About</a><a href="#services" className="glass-nav-link" onClick={() => setMobileMenuOpen(false)}>Services</a><a href="/shop" className="glass-nav-link" onClick={() => setMobileMenuOpen(false)}>Shop</a><a href="#projects" className="glass-nav-link" onClick={() => setMobileMenuOpen(false)}>Projects</a><a href="#contact" className="glass-nav-link" onClick={() => setMobileMenuOpen(false)}>Contact</a></nav>}
        </header>
        <div className="relative z-10 mx-auto flex h-[calc(100%-94px)] max-w-7xl flex-col justify-end px-6 pb-20 md:px-10 md:pb-24">
          <div className="max-w-3xl"><p className="mb-6 flex items-center gap-3 text-xs font-medium tracking-[.2em] text-[#46d6d2]"><span className="size-1.5 rounded-full bg-[#46d6d2]" />{slide.eyebrow}</p><h1 className="whitespace-pre-line text-balance text-6xl font-medium leading-[.98] tracking-[-.055em] md:text-8xl lg:text-[112px]">{slide.title}</h1><p className="mt-7 max-w-lg text-base leading-7 text-white/68 md:text-lg">{slide.description}</p><a href="#projects" className="mt-9 inline-flex items-center gap-3 rounded-full bg-[#46d6d2] px-6 py-3 text-sm font-semibold text-[#062328] transition hover:bg-white">Explore work <ArrowUpRight className="size-4" /></a></div>
          <div className="mt-14 flex items-center justify-between border-t border-white/25 pt-5"><div className="flex items-center gap-3 text-xs text-white/65"><span className="text-white">{String(safeActive + 1).padStart(2, '0')}</span><span className="h-px w-16 bg-white/35"><span className="block h-px bg-[#ef5b5b] transition-all duration-700" style={{ width: `${((safeActive + 1) / Math.max(slides.length, 1)) * 100}%` }} /></span><span>{String(slides.length).padStart(2, '0')}</span></div><span className="hidden text-xs text-white/60 sm:block">{slide.label}</span><div className="flex items-center gap-2"><button onClick={() => setPlaying(!playing)} className="glass-button flex size-10 items-center justify-center rounded-full" aria-label={playing ? 'Pause slideshow' : 'Play slideshow'}>{playing ? <Pause className="size-3" /> : <Play className="size-3" />}</button><button onClick={() => setActive((active - 1 + slides.length) % slides.length)} className="glass-button flex size-10 items-center justify-center rounded-full" aria-label="Previous slide"><ChevronLeft className="size-4" /></button><button onClick={() => setActive((active + 1) % slides.length)} className="glass-button flex size-10 items-center justify-center rounded-full" aria-label="Next slide"><ChevronRight className="size-4" /></button></div></div>
        </div>
      </section>

      <section id="about" data-reveal className="reveal-section mx-auto max-w-7xl px-6 py-24 md:px-10 lg:py-36"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr] lg:gap-24"><p className="text-sm font-medium uppercase tracking-[.16em] text-primary">{standardCopy.standard_eyebrow || '/ The Fazco standard'}</p><div><h2 className="text-balance text-4xl font-medium leading-tight tracking-[-.045em] md:text-6xl">{standardCopy.standard_title || 'Good lighting starts'}<br /><span className="text-muted-foreground">{standardCopy.standard_title_accent || 'with a better question.'}</span></h2><p className="mt-8 max-w-xl text-base leading-8 text-muted-foreground">{standardCopy.standard_description || 'Tell us how the space should feel, move and perform. We will help you choose the right balance of architectural character, reliable electrical infrastructure and responsible energy use.'}</p></div></div><div className="mt-20 grid gap-4 md:grid-cols-3">{(['01', '02', '03'] as const).map((number) => <article key={number} className="glass-card rounded-3xl p-7"><span className="text-3xl text-primary">{number}</span><h3 className="mt-12 text-xl font-medium">{standardCopy[`standard_card_${number}_title`] || ({ '01': 'Start with the mood', '02': 'Choose the performance', '03': 'Make it feel effortless' }[number])}</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{standardCopy[`standard_card_${number}_description`] || ({ '01': 'Share references, materials and the atmosphere you want people to remember.', '02': 'We recommend fixtures and systems that respect the project, budget and long-term use.', '03': 'Our team coordinates design, supply and installation into one clear experience.' }[number])}</p></article>)}</div></section>

      <section id="packages" data-reveal className="reveal-section border-y border-border bg-secondary px-6 py-24 md:px-10 lg:py-32"><div className="mx-auto max-w-7xl"><div className="mb-14 max-w-2xl"><p className="mb-5 text-sm font-medium uppercase tracking-[.16em] text-primary">/ Packages</p><h2 className="text-4xl font-medium tracking-tight md:text-6xl">A clear place to start.</h2><p className="mt-5 text-sm leading-7 text-muted-foreground">Three focused ways to bring Fazco into your next space. Each package can be tailored after a first conversation.</p></div><div className="package-grid grid gap-4 lg:grid-cols-3"><article className="package-card package-card-bronze rounded-3xl p-7 md:p-9"><p className="package-accent text-sm">{packageCopy.package_bronze_label || 'Eco Bronze Basic'}</p><h3 className="mt-5 text-3xl font-medium">{packageCopy.package_bronze_title || 'Essential clarity.'}</h3><p className="mt-4 text-sm leading-7 text-muted-foreground">{packageCopy.package_bronze_description || 'A practical starting point for smaller residential or commercial spaces.'}</p><ul className="mt-8 flex flex-col gap-3 text-sm"><li>Lighting concept direction</li><li>Core electrical review</li><li>Focused fixture selection</li></ul></article><article className="package-card package-card-titanium rounded-3xl p-7 md:p-9"><p className="package-accent text-sm">{packageCopy.package_titanium_label || 'Pro Titanium'}</p><h3 className="mt-5 text-3xl font-medium">{packageCopy.package_titanium_title || 'Balanced ambition.'}</h3><p className="mt-4 text-sm leading-7 text-muted-foreground">{packageCopy.package_titanium_description || 'A coordinated design and systems package for projects ready to go further.'}</p><ul className="mt-8 flex flex-col gap-3 text-sm"><li>Full lighting design direction</li><li>Smart control planning</li><li>Installation coordination</li></ul></article><article className="package-card package-card-gold rounded-3xl p-7 md:p-9"><p className="package-accent text-sm">{packageCopy.package_gold_label || 'Golden VIP'}</p><h3 className="mt-5 text-3xl font-medium">{packageCopy.package_gold_title || 'Signature presence.'}</h3><p className="mt-4 text-sm leading-7 text-muted-foreground">{packageCopy.package_gold_description || 'An end-to-end creative and technical partnership for defining spaces.'}</p><ul className="mt-8 flex flex-col gap-3 text-sm"><li>Signature architectural lighting</li><li>Premium material direction</li><li>Dedicated project support</li></ul></article></div></div></section>

      <section id="services" data-reveal className="reveal-section border-y border-border bg-secondary px-6 py-24 md:px-10 lg:py-32"><div className="mx-auto max-w-7xl"><div className="mb-16 flex items-end justify-between"><div><p className="mb-5 text-sm font-medium uppercase tracking-[.16em] text-primary">/ What we do</p><h2 className="text-4xl font-medium tracking-tight md:text-6xl">Built for impact.</h2></div><Zap className="hidden size-10 text-[#ef5b5b] md:block" /></div><div className="grid gap-4 lg:grid-cols-3">{configuredServices.map(([number, defaultTitle, defaultText], index) => { const key = number; const title = serviceCopy[`service_${key}_title`] || defaultTitle; const text = serviceCopy[`service_${key}_description`] || defaultText; const image = serviceCopy[`service_${key}_image`]; return <article key={number} className="glass-card service-card group relative flex min-h-64 flex-col justify-between overflow-hidden rounded-3xl p-7 transition duration-500 hover:-translate-y-2 hover:border-primary/60 md:p-9">{image && <img src={image} alt="" aria-hidden="true" className="absolute inset-0 size-full object-cover opacity-[0.34] transition duration-700 group-hover:scale-105 group-hover:opacity-[0.70]" />}<div className="absolute inset-0 bg-gradient-to-t from-background/95 via-background/55 to-transparent" /><div className="relative z-10 flex justify-between text-sm text-muted-foreground"><span>{number}</span><ArrowUpRight className="size-5 transition group-hover:text-primary" /></div><div className="relative z-10"><h3 className="text-2xl font-medium">{title}</h3><p className="mt-3 max-w-xs text-sm leading-7 text-muted-foreground">{text}</p></div></article> })}</div></div></section>

      <section id="projects" data-reveal className="reveal-section mx-auto max-w-7xl px-6 py-24 md:px-10 lg:py-36"><div className="mb-14 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="mb-5 text-sm font-medium uppercase tracking-[.16em] text-primary">/ Selected work</p><h2 className="text-4xl font-medium tracking-tight md:text-6xl">Light in context.</h2></div><a href="#contact" className="flex items-center gap-2 text-sm text-muted-foreground transition hover:text-primary">View all projects <ArrowUpRight className="size-4" /></a></div><div className="grid gap-5 md:grid-cols-2">{projects.map((project) => <Project key={project.id} image={project.image} video={project.video} title={project.title} meta={project.meta} description={project.description} />)}{projects.length === 0 && <div className="col-span-full rounded-3xl border border-dashed border-border p-12 text-center text-sm text-muted-foreground">No projects are published yet.</div>}</div></section>

      <section data-reveal aria-label="Fazco motion graphic" className="reveal-section line-motion-section overflow-hidden border-y border-border bg-card px-6 py-16 md:px-10 lg:py-20"><div className="mx-auto flex max-w-7xl flex-col gap-10 md:flex-row md:items-center md:justify-between"><div className="max-w-sm"><p className="mb-4 text-sm font-medium uppercase tracking-[.16em] text-primary">{motion.eyebrow}</p><h2 className="text-3xl font-medium tracking-tight md:text-5xl">{motion.title}</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">{motion.description}</p></div><div className="line-art relative h-48 w-full max-w-2xl overflow-hidden rounded-3xl border border-primary/20 bg-[#f4fbfb]" aria-hidden="true"><span className="line-line line-line-one" /><span className="line-line line-line-two" /><span className="line-line line-line-three" /><span className="line-node line-node-one" /><span className="line-node line-node-two" /><span className="line-node line-node-three" /><span className="line-pulse line-pulse-one" /><span className="line-pulse line-pulse-two" /></div></div><div className="mx-auto mt-12 max-w-7xl overflow-hidden rounded-3xl border border-border bg-[#071c22]">{motion.video ? <video className="aspect-[21/7] w-full object-cover opacity-90" src={motion.video} autoPlay muted loop playsInline controls aria-label={motion.label || 'Fazco promotional film'} /> : <div className="flex aspect-[21/7] items-center justify-center text-sm text-white/60">No company film is configured yet.</div>}</div></section>

      <section id="contact" className="relative overflow-hidden border-t border-border bg-[#e9f7f6] px-6 py-28 text-[#08252b] md:px-10 lg:py-40"><div className="mx-auto max-w-7xl"><p className="mb-6 text-sm font-medium uppercase tracking-[.16em] text-[#119b9a]">/ Start a conversation</p><h2 className="max-w-4xl text-balance text-5xl font-medium leading-[1.02] tracking-[-.055em] md:text-8xl">Let&apos;s make<br /><span className="text-[#119b9a]">something visible.</span></h2><a href="mailto:fazco.email@gmail.com" className="mt-12 inline-flex items-center gap-3 rounded-full bg-[#08252b] px-6 py-3 text-sm font-semibold text-white transition hover:bg-[#ef5b5b]">fazco.email@gmail.com <ArrowUpRight className="size-4" /></a></div></section>
      <footer className="bg-[#08252b] px-6 py-14 text-white md:px-10"><div className="mx-auto grid max-w-7xl gap-12 md:grid-cols-[1.3fr_1fr_1fr_1fr]"><div><div className="flex items-center gap-3"><img src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/photo_7_2026-07-12_18-43-01-9uuKPIzDLFIPmlGt5ZWOKr8QzsQkX9.jpg" alt="Fazco logo" className="h-14 w-44 rounded-xl bg-black object-contain object-center opacity-100 ring-1 ring-white/20 md:h-16 md:w-52" /></div><p className="mt-5 max-w-xs text-sm leading-7 text-white/55">Electrical engineering and architectural lighting for spaces with a point of view.</p></div><div><p className="text-xs uppercase tracking-[.16em] text-white/40">Explore</p><div className="mt-5 flex flex-col gap-3 text-sm text-white/70"><a href="#about" className="hover:text-white">About Fazco</a><a href="#services" className="hover:text-white">Services</a><a href="#packages" className="hover:text-white">Packages</a><a href="#projects" className="hover:text-white">Projects</a></div></div><div><p className="text-xs uppercase tracking-[.16em] text-white/40">Contact</p><div className="mt-5 flex flex-col gap-3 text-sm text-white/70"><a href="mailto:fazco.email@gmail.com" className="hover:text-white">fazco.email@gmail.com</a><span>Tehran · Athens</span></div></div><div><p className="text-xs uppercase tracking-[.16em] text-white/40">Follow</p><div className="mt-5 flex flex-col gap-3 text-sm text-white/70"><a href="https://instagram.com/fazco_industries?igsh=MXZuaXFwbTQyYnRldA==" target="_blank" rel="noreferrer" className="hover:text-white">Instagram @fazco_industries</a><a href="/sign-in" className="hover:text-white">Client portal</a><a href="#contact" className="hover:text-white">Start a project</a></div></div></div><div className="mx-auto mt-14 flex max-w-7xl flex-col gap-3 border-t border-white/10 pt-6 text-xs text-white/40 md:flex-row md:items-center md:justify-between"><span>© 2026 Fazco. All rights reserved.</span><span>Electrical engineering · Architectural lighting</span></div></footer>
    </main>
  )
}

function Project({ image, video, title, meta, description, large = false }: { image: string; video?: string; title: string; meta: string; description?: string; large?: boolean }) {
  return <article className={`group relative min-h-[380px] overflow-hidden rounded-3xl ${large ? 'md:col-span-2 md:min-h-[600px]' : ''}`}>{video ? <video src={video} autoPlay muted loop playsInline controls className="absolute inset-0 size-full object-cover transition duration-700 group-hover:scale-105" aria-label={title} /> : <img src={image} alt={title} className="absolute inset-0 size-full object-cover transition duration-700 group-hover:scale-105" />}<div className="absolute inset-0 bg-gradient-to-t from-black/80 to-transparent" /><div className="absolute bottom-0 left-0 p-7 text-white md:p-10"><p className="text-xs text-[#46d6d2]">{meta}</p><h3 className="mt-3 text-2xl font-medium md:text-3xl">{title}</h3>{description && <p className="mt-2 max-w-md text-sm text-white/70">{description}</p>}</div></article>
}
