'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
export function CheckoutClient({ encodedItems }: { encodedItems: string }) {
  const router = useRouter(); const [form, setForm] = useState({ name: '', email: '', address: '' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { const response = await fetch('/api/checkout', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ items: JSON.parse(decodeURIComponent(encodedItems)), customer: form }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); if (data.url) window.location.href = data.url; else router.push(`/shop?order=${data.orderId}`) } catch (e) { setError(e instanceof Error ? e.message : 'Checkout failed.') } finally { setBusy(false) } }
  return <div className="mx-auto grid max-w-5xl gap-12 px-6 py-20 md:grid-cols-[1fr_360px] md:px-10"><div><p className="text-sm uppercase tracking-[.16em] text-primary">Secure checkout</p><h1 className="mt-4 text-5xl font-medium tracking-tight">Complete your order.</h1><form onSubmit={submit} className="mt-10 grid gap-5"><label className="grid gap-2 text-sm">Full name<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="h-12 rounded-xl border border-border bg-background px-4" /></label><label className="grid gap-2 text-sm">Email<input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} className="h-12 rounded-xl border border-border bg-background px-4" /></label><label className="grid gap-2 text-sm">Delivery address<textarea required value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })} className="min-h-28 rounded-xl border border-border bg-background p-4" /></label>{error && <p className="text-sm text-destructive">{error}</p>}<button disabled={busy || !encodedItems} className="rounded-full bg-primary px-5 py-4 text-sm font-medium text-primary-foreground disabled:opacity-50">{busy ? 'Processing…' : 'Continue to payment'}</button></form></div><aside className="rounded-3xl border border-border bg-card p-6"><h2 className="font-medium">Order summary</h2><p className="mt-3 text-sm text-muted-foreground">Your cart will be validated against live inventory before payment.</p><Link href={`/cart?items=${encodedItems}`} className="mt-8 block text-sm text-primary">Edit cart</Link></aside></div>
}
