import Link from 'next/link'
import { notFound } from 'next/navigation'
import { ArrowLeft, Check, ShoppingBag } from 'lucide-react'
import { getProductBySlug, formatPrice } from '@/lib/products'
import { ProductGallery } from '@/components/product-gallery'
import { ShopNavbar } from '@/components/shop-navbar'

type Params = { slug: string }
const lines = (value: string) => value.split(/\r?\n|,/).map((item) => item.trim()).filter(Boolean)

export default async function ProductPage({ params }: { params: Promise<Params> }) {
  const product = await getProductBySlug((await params).slug)
  if (!product || !product.active) notFound()
  const images = [product.image, product.imageTwo, product.imageThree]
  const technical = [['Dimension', product.dimensions, product.dimensionImage], ['CCT', product.cct, product.cctImage], ['Section', product.sectionDetail, product.sectionImage], ['Finish', product.finish, product.finishImage], ['Installation', product.installation, product.installationImage]].filter(([, value, image]) => value || image)
  const colors = lines(product.colorOptions)
  const colorImages = lines(product.colorImages)
  const logos = lines(product.installationLogos)
  return <main className="min-h-screen bg-background"><ShopNavbar /><div className="mx-auto max-w-7xl px-5 py-12 md:px-10 md:py-20"><Link href="/shop" className="mb-10 inline-flex items-center gap-2 text-sm text-muted-foreground transition hover:text-primary"><ArrowLeft className="size-4" />Back to shop</Link><div className="grid gap-10 lg:grid-cols-[1.05fr_.95fr] lg:gap-16"><ProductGallery name={product.name} images={images} /><div className="flex flex-col justify-center"><p className="text-sm uppercase tracking-[.16em] text-primary">{product.category || '/ Fazco collection'}</p><h1 className="mt-5 text-4xl font-medium tracking-tight md:text-6xl">{product.name}</h1><p className="mt-6 text-base leading-8 text-muted-foreground">{product.description}</p>{product.priceInCents > 0 && <span className="mt-8 text-2xl font-medium">{formatPrice(product.priceInCents)}</span>}<button type="button" disabled={product.stock < 1} className="mt-8 inline-flex w-fit items-center gap-2 rounded-full bg-primary px-5 py-3 text-sm font-medium text-primary-foreground transition hover:opacity-90 disabled:cursor-not-allowed disabled:opacity-50"><ShoppingBag className="size-4" />Add to cart</button></div></div><div className="mt-20 grid gap-5 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-sm uppercase tracking-[.16em] text-primary">/ Product details</p><h2 className="mt-4 text-3xl font-medium">Made to be understood.</h2></div><div className="grid gap-4 lg:grid-cols-2 lg:items-start">{product.uses && <DetailList title="Uses" items={lines(product.uses)} />}{product.features && <DetailList title="Features" items={lines(product.features)} />}</div></div>{technical.length > 0 && <section className="mt-20 space-y-8">{technical.map(([title, value, image]) => <TechnicalSection key={title} title={title} value={value} image={image} dimension={title === 'Dimension' ? { length: product.dimensionLength, width: product.dimensionWidth, height: product.dimensionHeight, unit: product.dimensionUnit, note: product.dimensionNote } : undefined} installation={title === 'Installation' ? { radiation: product.radiationImage, standards: product.logosImage, logos, colors } : undefined} />)}</section>}</div></main>
}

function DetailList({ title, items }: { title: string; items: string[] }) { return <section className="detail-card rounded-2xl border border-border/70 bg-card/80 p-6 shadow-sm"><h3 className="text-lg font-medium tracking-tight">{title}</h3><ul className="mt-4 grid gap-3 text-sm leading-6 text-muted-foreground">{items.map((item) => <li key={item} className="flex gap-2"><Check className="mt-1 size-4 shrink-0 text-primary" />{item}</li>)}</ul></section> }

function TechnicalSection({ title, value, image, dimension, installation }: { title: string; value: string; image: string; dimension?: { length: string; width: string; height: string; unit: string; note: string }; installation?: { radiation: string; standards: string; logos: string[]; colors: string[] } }) { const items = lines(value); return <section className="technical-section grid gap-3 md:grid-cols-[9rem_1fr] md:items-stretch"><div className="flex items-center rounded-xl border border-border/70 bg-card/70 px-4 py-3 md:items-start md:justify-center md:pt-5"><h3 className="text-base font-medium tracking-tight md:text-lg">{title}</h3></div><div className="technical-panel rounded-2xl border border-border/60 bg-muted/55 p-5 shadow-sm md:p-7">{dimension && (dimension.length || dimension.width || dimension.height) ? <div className="overflow-hidden rounded-xl border border-border/70 bg-background"><table className="w-full text-left text-sm"><thead className="bg-muted text-xs uppercase tracking-wider text-muted-foreground"><tr><th className="px-4 py-3">Length</th><th className="px-4 py-3">Width</th><th className="px-4 py-3">Height</th></tr></thead><tbody><tr className="border-t border-border"><td className="px-4 py-4">{dimension.length || '—'} {dimension.unit}</td><td className="px-4 py-4">{dimension.width || '—'} {dimension.unit}</td><td className="px-4 py-4">{dimension.height || '—'} {dimension.unit}</td></tr></tbody></table>{dimension.note && <p className="border-t border-border px-4 py-3 text-xs text-muted-foreground">{dimension.note}</p>}</div> : <div className="grid gap-6 md:grid-cols-[1fr_.8fr] md:items-center">{image ? <img src={image} alt={`${title} drawing for product`} className="h-52 w-full rounded-xl object-contain" /> : <div className="flex min-h-36 items-center justify-center rounded-xl border border-dashed border-border bg-background/40 text-sm text-muted-foreground">Add a {title.toLowerCase()} image from Admin</div>}{items.length > 0 && <ul className="grid gap-2.5 text-sm leading-7 text-muted-foreground">{items.map((item) => <li key={item}>• {item}</li>)}</ul>}</div>}{installation && <div className="mt-6 grid gap-4 border-t border-border/60 pt-5 md:grid-cols-3">{installation.radiation && <img src={installation.radiation} alt="Radiation map" className="h-28 w-full rounded-lg bg-background object-contain" />}{installation.standards && <img src={installation.standards} alt="Product standards and logos" className="h-28 w-full rounded-lg bg-background object-contain" />}<div className="flex flex-wrap items-center gap-2">{installation.logos.map((logo) => <img key={logo} src={logo} alt="Installation logo" className="size-10 rounded border border-border bg-background object-contain p-1" />)}{installation.colors.map((color) => <span key={color} className="rounded-full border border-border bg-background px-2.5 py-1 text-xs">{color}</span>)}</div></div>}</div></section> }
